name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Modify
      run: |
        sed -i '' 's/O2/O3/g' configure
        chmod +x configure
    
    - name: Configure
      run: ./configure

    - name: Build
      run: make
    
    - name: Compress
      run: |
        mv src/srm ./
        zip srm.zip srm
    
    - uses: actions/upload-artifact@v3
      with:
        name: srm-macos
        path: srm.zip

  build-windows:
  
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Update MinGW
      run: choco upgrade mingw -y
    
    - name: Build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -G Ninja
        cmake --build build
    
    - uses: actions/upload-artifact@v3
      with:
        name: srm-windows
        path: build/srm.exe
